name: workservices
description: servicios de trabajo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_database: ^3.1.5
  firebase_storage: ^3.1.5


flutter:

  uses-material-design: true
